baseurl = "https://brunopacheco1.github.io"
title = "Bruno Pacheco"
theme = "coder-portfolio"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

[params]
    author = "Bruno Pacheco" 
    info = "Software Engineer"
    description = "Bruno Pacheco's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    hideCredits = false
    hideCopyright = false

    custom_css = []

    itemscentered = true

    rtl = false

    snsShare = true
    enableTwitterShare = true
    enableFacebookShare = true
    enableHatenaShare = true
    enableLineShare = true
    enableLinkedInShare = true

    thumbnail = "images/tn.png"

    langseparator = "|" 

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/brunopacheco1"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/brunopacheco1/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
